<?php

declare(strict_types=1);

use DG\BypassFinals;
use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__) . '/vendor/autoload.php';

// Repositories are `final` (see each class's own docblock — no legitimate
// reason to subclass one in real code) but PHPUnit's createMock()/
// createStub() need to generate a test double by subclassing, which is
// impossible for a final class. BypassFinals patches the `final` keyword
// out at require-time via a stream wrapper, so the classes stay honestly
// final in src/ while still being mockable in tests/Unit. Must run before
// anything under App\ is autoloaded, hence immediately after the composer
// autoloader above and before Dotenv/anything else.
BypassFinals::enable();

if (method_exists(Dotenv::class, 'bootEnv')) {
    (new Dotenv())->bootEnv(dirname(__DIR__) . '/.env');
}

if (($_SERVER['APP_DEBUG'] ?? false) !== false) {
    umask(0000);
}

// tests/Unit is plain PHPUnit\Framework\TestCase classes — no kernel, no
// database, by design (that's what makes them fast and dependency-free).
// `bin/phpunit --testsuite=unit` shouldn't need Postgres reachable at all,
// so skip the database bootstrap entirely for that invocation. Anything
// else (the default full run, or --testsuite=application) still needs it.
$rawArgv = $_SERVER['argv'] ?? null;
/** @var list<string> $argv */
$argv = is_array($rawArgv) ? $rawArgv : [];
$isUnitOnlyRun = in_array('--testsuite=unit', $argv, true)
    || (in_array('unit', $argv, true) && in_array('--testsuite', $argv, true));

if (!$isUnitOnlyRun) {
    // Symfony/Doctrine do not create the test database automatically, and
    // the JWT test keypair (config/jwt/test/) isn't generated by
    // docker/entrypoint.sh (that only covers the dev keypair) — this
    // replaces three manual steps the README used to document. All three
    // are idempotent (--if-not-exists / --skip-if-exists, and migrate
    // no-ops once current), so running them on every suite invocation is
    // safe and cheap.
    $console = dirname(__DIR__) . '/bin/console';
    foreach (
        [
            [$console, 'lexik:jwt:generate-keypair', '--skip-if-exists', '--no-interaction', '--env=test', '--quiet'],
            [$console, 'doctrine:database:create', '--if-not-exists', '--no-interaction', '--env=test', '--quiet'],
            [$console, 'doctrine:migrations:migrate', '--no-interaction', '--env=test', '--quiet'],
        ] as $command
    ) {
        $process = proc_open([PHP_BINARY, ...$command], [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
        if ($process === false) {
            throw new \RuntimeException('Failed to start ' . $command[1] . '.');
        }

        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        $output = ($stdout !== false ? $stdout : '') . ($stderr !== false ? $stderr : '');
        fclose($pipes[1]);
        fclose($pipes[2]);
        $exitCode = proc_close($process);

        if ($exitCode !== 0) {
            throw new \RuntimeException("Failed to prepare the test database ({$command[1]}):\n{$output}");
        }
    }
}
