<?php

declare(strict_types=1);

namespace App\DataFixtures;

use App\Entity\Organisation;

/**
 * The sample extract's charges, in delivery order. ch_0005 appears twice,
 * byte-identical — a redelivery, collapsed by dedupe. ch_0027 shares its
 * available_on date with everything po_0001 swept, yet po_0001 skips it:
 * the reason "pending" is derived from settlement linkage, never a date.
 */
final class ChargeFixtures extends LedgerRecordFixture
{
    #[\Override]
    public function getDependencies(): array
    {
        return [OrganisationFixtures::class];
    }

    #[\Override]
    protected function ingest(Organisation $organisation, array $records): array
    {
        $this->seeder->recordCharges($organisation, $records);

        return [];
    }

    #[\Override]
    public function records(): array
    {
        return [
            [
                'id' => 'ch_0013',
                'object' => 'charge',
                'created' => '2026-06-13T09:24:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4013',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0047',
                'object' => 'charge',
                'created' => '2026-06-14T13:32:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4047',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0007',
                'object' => 'charge',
                'created' => '2026-06-13T15:12:00Z',
                'amount' => 4500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4007',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 83],
                    ['type' => 'application_fee', 'amount' => 120],
                ],
                'net' => 4297,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0004',
                'object' => 'charge',
                'created' => '2026-06-13T12:06:00Z',
                'amount' => 3200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4004',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 65],
                    ['type' => 'application_fee', 'amount' => 94],
                ],
                'net' => 3041,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0048',
                'object' => 'charge',
                'created' => '2026-06-14T14:34:00Z',
                'amount' => 1500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4048',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 41],
                    ['type' => 'application_fee', 'amount' => 60],
                ],
                'net' => 1399,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0059',
                'object' => 'charge',
                'created' => '2026-06-14T13:56:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4059',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0031',
                'object' => 'charge',
                'created' => '2026-06-14T09:00:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4031',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0026',
                'object' => 'charge',
                'created' => '2026-06-13T10:50:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4026',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0001',
                'object' => 'charge',
                'created' => '2026-06-13T09:00:00Z',
                'amount' => 1500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4001',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 41],
                    ['type' => 'application_fee', 'amount' => 60],
                ],
                'net' => 1399,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0056',
                'object' => 'charge',
                'created' => '2026-06-14T10:50:00Z',
                'amount' => 3200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4056',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 65],
                    ['type' => 'application_fee', 'amount' => 94],
                ],
                'net' => 3041,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0023',
                'object' => 'charge',
                'created' => '2026-06-13T19:44:00Z',
                'amount' => 2200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4023',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 51],
                    ['type' => 'application_fee', 'amount' => 74],
                ],
                'net' => 2075,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0042',
                'object' => 'charge',
                'created' => '2026-06-14T20:22:00Z',
                'amount' => 1500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4042',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 41],
                    ['type' => 'application_fee', 'amount' => 60],
                ],
                'net' => 1399,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0057',
                'object' => 'charge',
                'created' => '2026-06-14T11:52:00Z',
                'amount' => 1250,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4057',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 38],
                    ['type' => 'application_fee', 'amount' => 55],
                ],
                'net' => 1157,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0040',
                'object' => 'charge',
                'created' => '2026-06-14T18:18:00Z',
                'amount' => 4500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4040',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 83],
                    ['type' => 'application_fee', 'amount' => 120],
                ],
                'net' => 4297,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0017',
                'object' => 'charge',
                'created' => '2026-06-13T13:32:00Z',
                'amount' => 2200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4017',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 51],
                    ['type' => 'application_fee', 'amount' => 74],
                ],
                'net' => 2075,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0015',
                'object' => 'charge',
                'created' => '2026-06-13T11:28:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4015',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0036',
                'object' => 'charge',
                'created' => '2026-06-14T14:10:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4036',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0049',
                'object' => 'charge',
                'created' => '2026-06-14T15:36:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4049',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0046',
                'object' => 'charge',
                'created' => '2026-06-14T12:30:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4046',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0052',
                'object' => 'charge',
                'created' => '2026-06-14T18:42:00Z',
                'amount' => 1250,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4052',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 38],
                    ['type' => 'application_fee', 'amount' => 55],
                ],
                'net' => 1157,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0055',
                'object' => 'charge',
                'created' => '2026-06-14T09:48:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4055',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0041',
                'object' => 'charge',
                'created' => '2026-06-14T19:20:00Z',
                'amount' => 1250,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4041',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 38],
                    ['type' => 'application_fee', 'amount' => 55],
                ],
                'net' => 1157,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0018',
                'object' => 'charge',
                'created' => '2026-06-13T14:34:00Z',
                'amount' => 2200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4018',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 51],
                    ['type' => 'application_fee', 'amount' => 74],
                ],
                'net' => 2075,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0025',
                'object' => 'charge',
                'created' => '2026-06-13T09:48:00Z',
                'amount' => 4500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4025',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 83],
                    ['type' => 'application_fee', 'amount' => 120],
                ],
                'net' => 4297,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0003',
                'object' => 'charge',
                'created' => '2026-06-13T11:04:00Z',
                'amount' => 2200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4003',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 51],
                    ['type' => 'application_fee', 'amount' => 74],
                ],
                'net' => 2075,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0060',
                'object' => 'charge',
                'created' => '2026-06-14T14:58:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4060',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0002',
                'object' => 'charge',
                'created' => '2026-06-13T10:02:00Z',
                'amount' => 1250,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4002',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 38],
                    ['type' => 'application_fee', 'amount' => 55],
                ],
                'net' => 1157,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0014',
                'object' => 'charge',
                'created' => '2026-06-13T10:26:00Z',
                'amount' => 1250,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4014',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 38],
                    ['type' => 'application_fee', 'amount' => 55],
                ],
                'net' => 1157,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0010',
                'object' => 'charge',
                'created' => '2026-06-13T18:18:00Z',
                'amount' => 1500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4010',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 41],
                    ['type' => 'application_fee', 'amount' => 60],
                ],
                'net' => 1399,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0043',
                'object' => 'charge',
                'created' => '2026-06-14T09:24:00Z',
                'amount' => 2200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4043',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 51],
                    ['type' => 'application_fee', 'amount' => 74],
                ],
                'net' => 2075,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0011',
                'object' => 'charge',
                'created' => '2026-06-13T19:20:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4011',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0033',
                'object' => 'charge',
                'created' => '2026-06-14T11:04:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4033',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0005',
                'object' => 'charge',
                'created' => '2026-06-13T13:08:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4005',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0005',
                'object' => 'charge',
                'created' => '2026-06-13T13:08:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4005',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0039',
                'object' => 'charge',
                'created' => '2026-06-14T17:16:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4039',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0019',
                'object' => 'charge',
                'created' => '2026-06-13T15:36:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4019',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0029',
                'object' => 'charge',
                'created' => '2026-06-13T13:56:00Z',
                'amount' => 3200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4029',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 65],
                    ['type' => 'application_fee', 'amount' => 94],
                ],
                'net' => 3041,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0022',
                'object' => 'charge',
                'created' => '2026-06-13T18:42:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4022',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0032',
                'object' => 'charge',
                'created' => '2026-06-14T10:02:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4032',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0034',
                'object' => 'charge',
                'created' => '2026-06-14T12:06:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4034',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0054',
                'object' => 'charge',
                'created' => '2026-06-14T20:46:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4054',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0037',
                'object' => 'charge',
                'created' => '2026-06-14T15:12:00Z',
                'amount' => 1250,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4037',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 38],
                    ['type' => 'application_fee', 'amount' => 55],
                ],
                'net' => 1157,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0006',
                'object' => 'charge',
                'created' => '2026-06-13T14:10:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4006',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0053',
                'object' => 'charge',
                'created' => '2026-06-14T19:44:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4053',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0045',
                'object' => 'charge',
                'created' => '2026-06-14T11:28:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4045',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0012',
                'object' => 'charge',
                'created' => '2026-06-13T20:22:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4012',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0051',
                'object' => 'charge',
                'created' => '2026-06-14T17:40:00Z',
                'amount' => 3200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4051',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 65],
                    ['type' => 'application_fee', 'amount' => 94],
                ],
                'net' => 3041,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0016',
                'object' => 'charge',
                'created' => '2026-06-13T12:30:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4016',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0020',
                'object' => 'charge',
                'created' => '2026-06-13T16:38:00Z',
                'amount' => 1250,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4020',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 38],
                    ['type' => 'application_fee', 'amount' => 55],
                ],
                'net' => 1157,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0024',
                'object' => 'charge',
                'created' => '2026-06-13T20:46:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4024',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0058',
                'object' => 'charge',
                'created' => '2026-06-14T12:54:00Z',
                'amount' => 1500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4058',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 41],
                    ['type' => 'application_fee', 'amount' => 60],
                ],
                'net' => 1399,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0038',
                'object' => 'charge',
                'created' => '2026-06-14T16:14:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4038',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0030',
                'object' => 'charge',
                'created' => '2026-06-13T14:58:00Z',
                'amount' => 3200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4030',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 65],
                    ['type' => 'application_fee', 'amount' => 94],
                ],
                'net' => 3041,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0021',
                'object' => 'charge',
                'created' => '2026-06-13T17:40:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4021',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0050',
                'object' => 'charge',
                'created' => '2026-06-14T16:38:00Z',
                'amount' => 4500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4050',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 83],
                    ['type' => 'application_fee', 'amount' => 120],
                ],
                'net' => 4297,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0028',
                'object' => 'charge',
                'created' => '2026-06-13T12:54:00Z',
                'amount' => 1250,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4028',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 38],
                    ['type' => 'application_fee', 'amount' => 55],
                ],
                'net' => 1157,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0035',
                'object' => 'charge',
                'created' => '2026-06-14T13:08:00Z',
                'amount' => 2200,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4035',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 51],
                    ['type' => 'application_fee', 'amount' => 74],
                ],
                'net' => 2075,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0044',
                'object' => 'charge',
                'created' => '2026-06-14T10:26:00Z',
                'amount' => 1250,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4044',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 38],
                    ['type' => 'application_fee', 'amount' => 55],
                ],
                'net' => 1157,
                'available_on' => '2026-06-17',
            ],
            [
                'id' => 'ch_0027',
                'object' => 'charge',
                'created' => '2026-06-13T11:52:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4027',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0008',
                'object' => 'charge',
                'created' => '2026-06-13T16:14:00Z',
                'amount' => 2500,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4008',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 55],
                    ['type' => 'application_fee', 'amount' => 80],
                ],
                'net' => 2365,
                'available_on' => '2026-06-16',
            ],
            [
                'id' => 'ch_0009',
                'object' => 'charge',
                'created' => '2026-06-13T17:16:00Z',
                'amount' => 800,
                'currency' => 'gbp',
                'status' => 'succeeded',
                'order_ref' => 'ORD-4009',
                'fee_details' => [
                    ['type' => 'stripe_fee', 'amount' => 31],
                    ['type' => 'application_fee', 'amount' => 46],
                ],
                'net' => 723,
                'available_on' => '2026-06-16',
            ],
        ];
    }
}
